---
- name: Konfigurasi SNMP pada Switch
  hosts: all
  gather_facts: no

  tasks:
    - name: Jalankan perintah konfigurasi SNMP via SSH
      ansible.builtin.shell: |
        configure terminal
        snmp-server community rahasiaKomunitas ro
        snmp-server enable traps
        end
        write
      register: ssh_output

    - name: Tampilkan hasil eksekusi dari Switch
      ansible.builtin.debug:
        var: ssh_output.stdout_lines
