[switches]
sw-ruijie-core-oob ansible_host=192.168.30.2

[switches:vars]
ansible_connection=ansible.builtin.ssh
ansible_user=dcadmin

# Tambahkan baris sakti di bawah ini untuk mengizinkan ssh-rsa lama
ansible_ssh_common_args='-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
